plugins {
    `maven-publish`
    id("libsl-publish")
    alias(libs.plugins.moddev)
    alias(libs.plugins.fg.main)
    alias(libs.plugins.fg.rm)
}

val modId = rootProject.property("mod_id")!! as String
val minecraftVersion = rootProject.property("minecraft_version")!! as String
val forgeVersion = rootProject.property("forge_version")!! as String

renamer.enableMixinRefmaps {
    config("$modId.mixins.json")
}

renamer.classes(tasks.named<Jar>("jar")) {
    archiveClassifier.set("srg")
    // We need to use the generated mappings, which includes things generated by the annotation processor
    mappings(renamer.mixin.generatedMappings)
}

minecraft {
    useDefaultAccessTransformer()
}

repositories {
    minecraft.mavenizer(this)
}

dependencies {
    implementation(minecraft.dependency("net.minecraftforge:forge:$minecraftVersion-$forgeVersion"))
    annotationProcessor("net.minecraftforge:eventbus-validator:7.0.5")
    annotationProcessor("org.spongepowered:mixin:0.8.7:processor")

    jarJar(rootProject.libs.snakeyaml)
    implementation(rootProject.libs.snakeyaml)
    jarJar(rootProject.libs.pkg.sewlia.config)
    implementation(rootProject.libs.pkg.sewlia.config)
    jarJar(libs.pkg.tinyutils)
    implementation(libs.pkg.tinyutils)
}

renamer.mappings(minecraft.dependency.toSrg)

tasks {
    jarJar {
        enabled = true
    }

    named<Jar>("jar") {
        manifest {
            attributes["Automatic-Module-Name"] = "one.pkg.libsl.neoforge"
        }
    }

    withType<Javadoc> {
        val o = options as StandardJavadocDocletOptions
        o.encoding = "UTF-8"
        o.source = "17"

        o.use()
    }
}

/*
neoForge {
    version = rootProject.property("neoforge_version")!! as String

    val at = project(":modcommon").file("src/main/resources/META-INF/accesstransformer.cfg")
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }

    mods {
        create("libsl") {
            sourceSet(sourceSets.main.get())
        }
    }
}
*/